### ISSUE TITLE
Actidiag 0.5 is broken

### ISSUE THREAD

**Issue by tk0miya** [blockdiag/actdiag#1]
After upgrading actdiag:

```
#!sh

$ actdiag --help
Traceback (most recent call last):
  File "/home/simon/lib/virtualenvs/adele-doc/bin/actdiag", line 9, in <module>
    load_entry_point('actdiag==0.5.0', 'console_scripts', 'actdiag')()
  File "/home/simon/lib/virtualenvs/adele-doc/lib/python2.7/site-packages/actdiag/command.py", line 28, in main
    return ActdiagApp().run()
TypeError: run() takes exactly 2 arguments (1 given)
```

It seems that actdiag/command.py needs to be updated, taking example on blockdiag, this works for me:

```
#!python

def main(args=sys.argv[1:]):
    return ActdiagApp().run(args)
```

----------------------------------------
- Bitbucket: https://bitbucket.org/blockdiag/actdiag/issue/1
- Originally reported by: [saimon](https://bitbucket.org/saimon)
- Originally created at: 2013-10-21T11:25:39.774

**Comment by tk0miya** [comment]
_From Radek Marik on 2014-04-02 08:02:40+00:00_

The issue should be treated more general. The current implementation seems to follow a kind of 'stack-based' assignments of method calls and returns. I have not found any way how to specify what instance activation a given method call should be linked to. GraphViz uses a notion of ports. What about to extend the syntax in similar way, i.e. to enable a use of activity labels extending instance labels? For example:
{
  A -> C:0;
  B -> C:1;
  A <-- C:0;
  B <-- C:1;
}
For example, this would enable to diagram a number of threads under one instance (like HTTP pipelining, etc in my case :-)).
